const express = require('express');
const router = express.Router();
const usersController = require('../controllers/usersController');
const auth = require('../middleware/authMiddleware');
const { registerValidator, loginValidator, updateProfileValidator } = require('../middleware/validators');
const { upload, optimizeImage } = require('../middleware/imageOptimizer');
router.get('/', usersController.getAllUsers);
router.post('/register', registerValidator, usersController.createUser);
router.post('/login', loginValidator, usersController.loginUser);
router.post('/logout', auth, usersController.logoutUser);
router.delete('/me', auth, usersController.deleteSelf);
router.put('/me/password', auth, usersController.updatePassword);
router.post('/forgot-password', usersController.forgotPassword);
router.post('/reset-password', usersController.resetPassword);
router.get('/featured', usersController.getFeaturedInstructor);
router.get('/:id', usersController.getUserById);
router.put('/:id', auth, updateProfileValidator, usersController.updateUser);
router.post('/:id/picture', auth, upload.single('profile_picture'), optimizeImage('profiles', 800), usersController.uploadPicture);
router.delete('/:id/picture', auth, usersController.deletePicture);
router.post('/:id/upgrades/:type', auth, usersController.buyUpgrade);
router.post('/:id/feature', auth, usersController.buyFeaturedSpot);
router.put('/:id/instructor-profile', auth, usersController.updateInstructorProfile);
router.post('/:id/contact', usersController.contactInstructor);

module.exports = router;
